name: BugsBlepFishingAddon
version: '1.0-SNAPSHOT'
main: bug.example.diamond.Diamond
api-version: '1.21'
depend:
  - BlepFishing

commands:
  configgui:
    description: Opens the config GUI
    usage: /configgui